//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt {
    
    
    public partial class loginSignup {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// textKullaniciAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textKullaniciAd;
        
        /// <summary>
        /// textPasswordP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textPasswordP;
        
        /// <summary>
        /// ButtonLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ButtonLogin;
        
        /// <summary>
        /// textTC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textTC;
        
        /// <summary>
        /// textCreateEmployeeName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textCreateEmployeeName;
        
        /// <summary>
        /// textCreateEmployeeSurname control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox textCreateEmployeeSurname;
        
        /// <summary>
        /// passwordCreateP control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox passwordCreateP;
        
        /// <summary>
        /// passwordCreateP2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox passwordCreateP2;
        
        /// <summary>
        /// signUpButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated rafId.
        /// To modify move rafId declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button signUpButton;
    }
}
