//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt {
    
    
    public partial class MapDesign {
        
        /// <summary>
        /// DropDownList_SubCategorySelect control.
        /// </summary>
        /// <remarks>
        /// Auto-generated id.
        /// To modify move id declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList_SubCategorySelect;
        
        /// <summary>
        /// RadioButton_Square control.
        /// </summary>
        /// <remarks>
        /// Auto-generated id.
        /// To modify move id declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RadioButton_Square;
        
        /// <summary>
        /// RadioButton_Circle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated id.
        /// To modify move id declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RadioButton_Circle;
        
        /// <summary>
        /// RadioButton_Triangle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated id.
        /// To modify move id declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton RadioButton_Triangle;
        
        /// <summary>
        /// btnAddShelf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated id.
        /// To modify move id declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnAddShelf;
    }
}
