//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindIt {
    
    
    public partial class ProductOperations {
        
        /// <summary>
        /// txtUrunAd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtUrunAd;
        
        /// <summary>
        /// txtBarkod control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtBarkod;
        
        /// <summary>
        /// DropDownListCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownListCategory;
        
        /// <summary>
        /// Label_CurrentCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_CurrentCategory;
        
        /// <summary>
        /// DropDownListSubCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownListSubCategory;
        
        /// <summary>
        /// Label_CurrentSubCategory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_CurrentSubCategory;
        
        /// <summary>
        /// txtCost control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCost;
        
        /// <summary>
        /// txtStock control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtStock;
        
        /// <summary>
        /// txtFeatures control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFeatures;
        
        /// <summary>
        /// Label_SearchNotFound control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Label_SearchNotFound;
        
        /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;
        
        /// <summary>
        /// btnProductAdd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProductAdd;
        
        /// <summary>
        /// btnProductDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProductDelete;
        
        /// <summary>
        /// btnProductUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated sekil.
        /// To modify move sekil declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnProductUpdate;
    }
}
